let nodes = [
    { name: "0", x: 100, y: 100, r: 12, tag: "Cliente 1" },
    { name: "1", x: 100, y: 250, r: 6, tag: "Cliente 2" },
    { name: "2", x: 100, y: 400, r: 20, tag: "Cliente 3" },
    { name: "3", x: 100, y: 550, r: 25, tag: "Cliente 4" },
    { name: "4", x: 430, y: 150, r: 9, tag: "Producto 1" },
    { name: "5", x: 430, y: 220, r: 30, tag: "Producto 2" },
    { name: "6", x: 430, y: 290, r: 27, tag: "Producto 3" },
    { name: "7", x: 430, y: 340, r: 11, tag: "Producto 4" },
    { name: "8", x: 430, y: 420, r: 32, tag: "Producto 5" },
    { name: "9", x: 430, y: 530, r: 15, tag: "Producto 6" },
    { name: "10", x: 700, y: 100, r: 21, tag: "Cliente 5" },
    { name: "11", x: 700, y: 250, r: 30, tag: "Cliente 6" },
    { name: "12", x: 700, y: 400, r: 23, tag: "Cliente 7" },
    { name: "13", x: 700, y: 550, r: 19, tag: "Cliente 8" },
];
let edges = [
    { source: nodes[0], target: nodes[4] },
    { source: nodes[0], target: nodes[9] },
    { source: nodes[0], target: nodes[6] },
    { source: nodes[0], target: nodes[7] },
    { source: nodes[1], target: nodes[5] },
    { source: nodes[1], target: nodes[4] },
    { source: nodes[1], target: nodes[6] },
    { source: nodes[1], target: nodes[7] },
    { source: nodes[1], target: nodes[9] },
    { source: nodes[2], target: nodes[8] },
    { source: nodes[2], target: nodes[9] },
    { source: nodes[2], target: nodes[5] },
    { source: nodes[3], target: nodes[4] },
    { source: nodes[3], target: nodes[8] },
    { source: nodes[3], target: nodes[6] },
    { source: nodes[3], target: nodes[5] },
    { source: nodes[3], target: nodes[7] },
    { source: nodes[3], target: nodes[9] },
    { source: nodes[10], target: nodes[8] },
    { source: nodes[10], target: nodes[9] },
    { source: nodes[10], target: nodes[5] },
    { source: nodes[11], target: nodes[4] },
    { source: nodes[11], target: nodes[8] },
    { source: nodes[11], target: nodes[6] },
    { source: nodes[12], target: nodes[5] },
    { source: nodes[12], target: nodes[7] },
    { source: nodes[13], target: nodes[9] },
];

